## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring.datasource.platform=postgres
spring.database.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/pird
spring.datasource.username=pird
spring.datasource.password=pird
# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Para exibir os comandos SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Para o hibernate nao fazer alteracoes na estrutura do banco de dados
spring.jpa.hibernate.ddl-auto=none

# Para funcionar o swagger
spring.mvc.pathmatch.matching-strategy=ant-path-matcher

# Security

spring.Security.login.username = "admin"
spring.Security.login.password = admin